### ISSUE TITLE
Update blacklight to 7 stable in gemspec

### ISSUE THREAD

**Issue by bbarberBPL** [boston-library/commonwealth-vlr-engine#32]
Blacklight is currently capped to 7.13.2 But the current stable is  7.19.2. Advise an update for any bug fixes/enhancements

**Comment by ebenenglish** [comment]
Updated dependency to `~> 7.19.0` in https://github.com/boston-library/commonwealth-vlr-engine/commit/2b3bd8b9efd2d07f2253afe1810c5ba0efdbd2b2.

This is the latest `7.*` version that we can upgrade to without a massive overhaul.
